// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema9 extends i0.VersionedSchema {
  Schema9({required super.database}) : super(version: 9);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    equipmentProfiles,
    devices,
    cameraModules,
    opticalRigs,
    locationProfiles,
    astroTargets,
    sessionLogs,
    captureBlocks,
  ];
  late final Shape0 equipmentProfiles = Shape0(
    source: i0.VersionedTable(
      entityName: 'equipment_profiles',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 devices = Shape1(
    source: i0.VersionedTable(
      entityName: 'devices',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_2, _column_13, _column_14],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 cameraModules = Shape2(
    source: i0.VersionedTable(
      entityName: 'camera_modules',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_15,
        _column_1,
        _column_2,
        _column_13,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 opticalRigs = Shape3(
    source: i0.VersionedTable(
      entityName: 'optical_rigs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_21,
        _column_22,
        _column_10,
        _column_23,
        _column_24,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 locationProfiles = Shape4(
    source: i0.VersionedTable(
      entityName: 'location_profiles',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 astroTargets = Shape5(
    source: i0.VersionedTable(
      entityName: 'astro_targets',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 sessionLogs = Shape6(
    source: i0.VersionedTable(
      entityName: 'session_logs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_52,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 captureBlocks = Shape7(
    source: i0.VersionedTable(
      entityName: 'capture_blocks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_53,
        _column_54,
        _column_55,
        _column_56,
        _column_57,
        _column_58,
        _column_59,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get manufacturer =>
      columnsByName['manufacturer']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get cameraModel =>
      columnsByName['camera_model']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get sensorWidth =>
      columnsByName['sensor_width']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get sensorHeight =>
      columnsByName['sensor_height']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get pixelPitch =>
      columnsByName['pixel_pitch']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get resolutionWidth =>
      columnsByName['resolution_width']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get resolutionHeight =>
      columnsByName['resolution_height']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get focalLength =>
      columnsByName['focal_length']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get aperture =>
      columnsByName['aperture']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get averageRawFileSizeMB =>
      columnsByName['average_raw_file_size_m_b']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get rotation =>
      columnsByName['rotation']! as i1.GeneratedColumn<double>;
}

i1.GeneratedColumn<int> _column_0(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'manufacturer',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'camera_model',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_4(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'sensor_width',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_5(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'sensor_height',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_6(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'pixel_pitch',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_7(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'resolution_width',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_8(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'resolution_height',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_9(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'focal_length',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_10(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'aperture',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_11(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'average_raw_file_size_m_b',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_12(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'rotation',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get manufacturer =>
      columnsByName['manufacturer']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get model =>
      columnsByName['model']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'model',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'notes',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get deviceId =>
      columnsByName['device_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get manufacturer =>
      columnsByName['manufacturer']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get model =>
      columnsByName['model']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get sensorWidthMm =>
      columnsByName['sensor_width_mm']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get sensorHeightMm =>
      columnsByName['sensor_height_mm']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get resolutionWidthPx =>
      columnsByName['resolution_width_px']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get resolutionHeightPx =>
      columnsByName['resolution_height_px']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get pixelPitchUm =>
      columnsByName['pixel_pitch_um']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get averageRawFileSizeMB =>
      columnsByName['average_raw_file_size_m_b']! as i1.GeneratedColumn<double>;
}

i1.GeneratedColumn<int> _column_15(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'device_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES devices(id)',
    );
i1.GeneratedColumn<double> _column_16(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'sensor_width_mm',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_17(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'sensor_height_mm',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_18(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'resolution_width_px',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_19(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'resolution_height_px',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_20(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'pixel_pitch_um',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get cameraModuleId =>
      columnsByName['camera_module_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get focalLengthMm =>
      columnsByName['focal_length_mm']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get aperture =>
      columnsByName['aperture']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get trackingState =>
      columnsByName['tracking_state']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get rotationDegrees =>
      columnsByName['rotation_degrees']! as i1.GeneratedColumn<double>;
}

i1.GeneratedColumn<int> _column_21(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'camera_module_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES camera_modules(id)',
    );
i1.GeneratedColumn<double> _column_22(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'focal_length_mm',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'tracking_state',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'unknown\'',
      defaultValue: const i1.CustomExpression('\'unknown\''),
    );
i1.GeneratedColumn<double> _column_24(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'rotation_degrees',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get latitude =>
      columnsByName['latitude']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get longitude =>
      columnsByName['longitude']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get elevation =>
      columnsByName['elevation']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get bortleClass =>
      columnsByName['bortle_class']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<double> _column_25(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'latitude',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_26(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'longitude',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_27(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'elevation',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_28(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'bortle_class',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 4',
      defaultValue: const i1.CustomExpression('4'),
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get catalogId =>
      columnsByName['catalog_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get commonName =>
      columnsByName['common_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get rightAscension =>
      columnsByName['right_ascension']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get declination =>
      columnsByName['declination']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'catalog_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_30(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'common_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_31(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'right_ascension',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_32(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'declination',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_33(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get targetName =>
      columnsByName['target_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get equipmentName =>
      columnsByName['equipment_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get sessionDate =>
      columnsByName['session_date']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get locationName =>
      columnsByName['location_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get bortleScale =>
      columnsByName['bortle_scale']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get plannedLightFrames =>
      columnsByName['planned_light_frames']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get plannedDarkFrames =>
      columnsByName['planned_dark_frames']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get plannedFlatFrames =>
      columnsByName['planned_flat_frames']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get plannedBiasFrames =>
      columnsByName['planned_bias_frames']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get integrationTimeSeconds =>
      columnsByName['integration_time_seconds']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get focalLength =>
      columnsByName['focal_length']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get aperture =>
      columnsByName['aperture']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get temperature =>
      columnsByName['temperature']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get humidity =>
      columnsByName['humidity']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get cloudCover =>
      columnsByName['cloud_cover']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get actualLightFrames =>
      columnsByName['actual_light_frames']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get rejectedFrames =>
      columnsByName['rejected_frames']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get environmentalNotes =>
      columnsByName['environmental_notes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get processingNotes =>
      columnsByName['processing_notes']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_34(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'target_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_35(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'equipment_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_36(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'session_date',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_37(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'location_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_38(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'bortle_scale',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_39(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'planned_light_frames',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_40(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'planned_dark_frames',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_41(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'planned_flat_frames',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_42(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'planned_bias_frames',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_43(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'integration_time_seconds',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_44(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'focal_length',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_45(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'aperture',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_46(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'temperature',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_47(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'humidity',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_48(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'cloud_cover',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_49(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'actual_light_frames',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_50(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'rejected_frames',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_51(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'environmental_notes',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_52(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'processing_notes',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get sessionLogId =>
      columnsByName['session_log_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get frameType =>
      columnsByName['frame_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get filterName =>
      columnsByName['filter_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get exposureTimeSeconds =>
      columnsByName['exposure_time_seconds']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get frameCount =>
      columnsByName['frame_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get binning =>
      columnsByName['binning']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get gainIso =>
      columnsByName['gain_iso']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_53(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'session_log_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES session_logs(id)',
    );
i1.GeneratedColumn<String> _column_54(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'frame_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_55(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'filter_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_56(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'exposure_time_seconds',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_57(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'frame_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_58(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'binning',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 1',
      defaultValue: const i1.CustomExpression('1'),
    );
i1.GeneratedColumn<String> _column_59(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'gain_iso',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

final class Schema10 extends i0.VersionedSchema {
  Schema10({required super.database}) : super(version: 10);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    devices,
    cameraModules,
    opticalRigs,
    locationProfiles,
    astroTargets,
    sessionLogs,
    captureBlocks,
  ];
  late final Shape1 devices = Shape1(
    source: i0.VersionedTable(
      entityName: 'devices',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_2, _column_13, _column_14],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 cameraModules = Shape2(
    source: i0.VersionedTable(
      entityName: 'camera_modules',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_60,
        _column_1,
        _column_2,
        _column_13,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 opticalRigs = Shape3(
    source: i0.VersionedTable(
      entityName: 'optical_rigs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_61,
        _column_22,
        _column_10,
        _column_23,
        _column_24,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 locationProfiles = Shape4(
    source: i0.VersionedTable(
      entityName: 'location_profiles',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 astroTargets = Shape5(
    source: i0.VersionedTable(
      entityName: 'astro_targets',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 sessionLogs = Shape6(
    source: i0.VersionedTable(
      entityName: 'session_logs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_52,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 captureBlocks = Shape7(
    source: i0.VersionedTable(
      entityName: 'capture_blocks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_62,
        _column_54,
        _column_55,
        _column_56,
        _column_57,
        _column_58,
        _column_59,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

i1.GeneratedColumn<int> _column_60(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'device_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES devices(id)ON DELETE RESTRICT',
    );
i1.GeneratedColumn<int> _column_61(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'camera_module_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL REFERENCES camera_modules(id)ON DELETE RESTRICT',
    );
i1.GeneratedColumn<int> _column_62(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'session_log_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL REFERENCES session_logs(id)ON DELETE CASCADE',
    );

final class Schema11 extends i0.VersionedSchema {
  Schema11({required super.database}) : super(version: 11);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    devices,
    cameraModules,
    opticalRigs,
    locationProfiles,
    astroTargets,
    sessionLogs,
    captureBlocks,
  ];
  late final Shape1 devices = Shape1(
    source: i0.VersionedTable(
      entityName: 'devices',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_2, _column_13, _column_14],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 cameraModules = Shape2(
    source: i0.VersionedTable(
      entityName: 'camera_modules',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_60,
        _column_1,
        _column_2,
        _column_13,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 opticalRigs = Shape3(
    source: i0.VersionedTable(
      entityName: 'optical_rigs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_61,
        _column_22,
        _column_10,
        _column_23,
        _column_24,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 locationProfiles = Shape4(
    source: i0.VersionedTable(
      entityName: 'location_profiles',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 astroTargets = Shape5(
    source: i0.VersionedTable(
      entityName: 'astro_targets',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 sessionLogs = Shape6(
    source: i0.VersionedTable(
      entityName: 'session_logs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_52,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 captureBlocks = Shape8(
    source: i0.VersionedTable(
      entityName: 'capture_blocks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_62,
        _column_54,
        _column_55,
        _column_56,
        _column_57,
        _column_58,
        _column_63,
        _column_64,
        _column_65,
        _column_66,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get sessionLogId =>
      columnsByName['session_log_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get frameType =>
      columnsByName['frame_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get filterName =>
      columnsByName['filter_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get exposureTimeSeconds =>
      columnsByName['exposure_time_seconds']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get frameCount =>
      columnsByName['frame_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get binning =>
      columnsByName['binning']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get position =>
      columnsByName['position']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get calibrationPolicy =>
      columnsByName['calibration_policy']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get gainKind =>
      columnsByName['gain_kind']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get gainValue =>
      columnsByName['gain_value']! as i1.GeneratedColumn<double>;
}

i1.GeneratedColumn<int> _column_63(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'position',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_64(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'calibration_policy',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_65(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'gain_kind',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'unknown\'',
      defaultValue: const i1.CustomExpression('\'unknown\''),
    );
i1.GeneratedColumn<double> _column_66(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'gain_value',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );

final class Schema12 extends i0.VersionedSchema {
  Schema12({required super.database}) : super(version: 12);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    devices,
    cameraModules,
    opticalRigs,
    locationProfiles,
    astroTargets,
    sessionLogs,
    captureBlocks,
  ];
  late final Shape1 devices = Shape1(
    source: i0.VersionedTable(
      entityName: 'devices',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_2, _column_13, _column_14],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 cameraModules = Shape2(
    source: i0.VersionedTable(
      entityName: 'camera_modules',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_60,
        _column_1,
        _column_2,
        _column_13,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 opticalRigs = Shape3(
    source: i0.VersionedTable(
      entityName: 'optical_rigs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_61,
        _column_22,
        _column_10,
        _column_23,
        _column_24,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 locationProfiles = Shape9(
    source: i0.VersionedTable(
      entityName: 'location_profiles',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_25,
        _column_26,
        _column_27,
        _column_67,
        _column_68,
        _column_69,
        _column_70,
        _column_71,
        _column_72,
        _column_73,
        _column_14,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 astroTargets = Shape5(
    source: i0.VersionedTable(
      entityName: 'astro_targets',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 sessionLogs = Shape6(
    source: i0.VersionedTable(
      entityName: 'session_logs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_52,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 captureBlocks = Shape8(
    source: i0.VersionedTable(
      entityName: 'capture_blocks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_62,
        _column_54,
        _column_55,
        _column_56,
        _column_57,
        _column_58,
        _column_63,
        _column_64,
        _column_65,
        _column_66,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get latitude =>
      columnsByName['latitude']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get longitude =>
      columnsByName['longitude']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get elevation =>
      columnsByName['elevation']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get bortleClass =>
      columnsByName['bortle_class']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get bortleSource =>
      columnsByName['bortle_source']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get bortleDate =>
      columnsByName['bortle_date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get sqm =>
      columnsByName['sqm']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get sqmSource =>
      columnsByName['sqm_source']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sqmDate =>
      columnsByName['sqm_date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get timeZone =>
      columnsByName['time_zone']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_67(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'bortle_class',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_68(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'bortle_source',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_69(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'bortle_date',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_70(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'sqm',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_71(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'sqm_source',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_72(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'sqm_date',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_73(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'time_zone',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

final class Schema13 extends i0.VersionedSchema {
  Schema13({required super.database}) : super(version: 13);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    devices,
    cameraModules,
    opticalRigs,
    locationProfiles,
    astroTargets,
    sessionLogs,
    captureBlocks,
    astroTargetsCatalogIdUnique,
  ];
  late final Shape1 devices = Shape1(
    source: i0.VersionedTable(
      entityName: 'devices',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_2, _column_13, _column_14],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 cameraModules = Shape2(
    source: i0.VersionedTable(
      entityName: 'camera_modules',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_60,
        _column_1,
        _column_2,
        _column_13,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 opticalRigs = Shape3(
    source: i0.VersionedTable(
      entityName: 'optical_rigs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_61,
        _column_22,
        _column_10,
        _column_23,
        _column_24,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 locationProfiles = Shape9(
    source: i0.VersionedTable(
      entityName: 'location_profiles',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_25,
        _column_26,
        _column_27,
        _column_67,
        _column_68,
        _column_69,
        _column_70,
        _column_71,
        _column_72,
        _column_73,
        _column_14,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 astroTargets = Shape10(
    source: i0.VersionedTable(
      entityName: 'astro_targets',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_74,
        _column_75,
        _column_76,
        _column_77,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 sessionLogs = Shape6(
    source: i0.VersionedTable(
      entityName: 'session_logs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_52,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 captureBlocks = Shape8(
    source: i0.VersionedTable(
      entityName: 'capture_blocks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_62,
        _column_54,
        _column_55,
        _column_56,
        _column_57,
        _column_58,
        _column_63,
        _column_64,
        _column_65,
        _column_66,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index astroTargetsCatalogIdUnique = i1.Index(
    'astro_targets_catalog_id_unique',
    'CREATE UNIQUE INDEX astro_targets_catalog_id_unique ON astro_targets (catalog_id) WHERE source LIKE \'seed:%\' OR source LIKE \'catalog:%\'',
  );
}

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get catalogId =>
      columnsByName['catalog_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get commonName =>
      columnsByName['common_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get rightAscension =>
      columnsByName['right_ascension']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get declination =>
      columnsByName['declination']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get epoch =>
      columnsByName['epoch']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get source =>
      columnsByName['source']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get angularSizeArcmin =>
      columnsByName['angular_size_arcmin']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get magnitude =>
      columnsByName['magnitude']! as i1.GeneratedColumn<double>;
}

i1.GeneratedColumn<String> _column_74(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'epoch',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'J2000\'',
      defaultValue: const i1.CustomExpression('\'J2000\''),
    );
i1.GeneratedColumn<String> _column_75(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_76(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'angular_size_arcmin',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_77(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'magnitude',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );

final class Schema14 extends i0.VersionedSchema {
  Schema14({required super.database}) : super(version: 14);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    devices,
    cameraModules,
    opticalRigs,
    locationProfiles,
    astroTargets,
    sessionLogs,
    captureBlocks,
    astroTargetsCatalogIdUnique,
  ];
  late final Shape1 devices = Shape1(
    source: i0.VersionedTable(
      entityName: 'devices',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_2, _column_13, _column_14],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 cameraModules = Shape2(
    source: i0.VersionedTable(
      entityName: 'camera_modules',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_60,
        _column_1,
        _column_2,
        _column_13,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 opticalRigs = Shape11(
    source: i0.VersionedTable(
      entityName: 'optical_rigs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_61,
        _column_22,
        _column_10,
        _column_23,
        _column_24,
        _column_78,
        _column_79,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 locationProfiles = Shape9(
    source: i0.VersionedTable(
      entityName: 'location_profiles',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_25,
        _column_26,
        _column_27,
        _column_67,
        _column_68,
        _column_69,
        _column_70,
        _column_71,
        _column_72,
        _column_73,
        _column_14,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 astroTargets = Shape10(
    source: i0.VersionedTable(
      entityName: 'astro_targets',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_74,
        _column_75,
        _column_76,
        _column_77,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 sessionLogs = Shape6(
    source: i0.VersionedTable(
      entityName: 'session_logs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_52,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 captureBlocks = Shape8(
    source: i0.VersionedTable(
      entityName: 'capture_blocks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_62,
        _column_54,
        _column_55,
        _column_56,
        _column_57,
        _column_58,
        _column_63,
        _column_64,
        _column_65,
        _column_66,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index astroTargetsCatalogIdUnique = i1.Index(
    'astro_targets_catalog_id_unique',
    'CREATE UNIQUE INDEX astro_targets_catalog_id_unique ON astro_targets (catalog_id) WHERE source LIKE \'seed:%\' OR source LIKE \'catalog:%\'',
  );
}

class Shape11 extends i0.VersionedTable {
  Shape11({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get cameraModuleId =>
      columnsByName['camera_module_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get focalLengthMm =>
      columnsByName['focal_length_mm']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get aperture =>
      columnsByName['aperture']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get trackingState =>
      columnsByName['tracking_state']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get rotationDegrees =>
      columnsByName['rotation_degrees']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get apertureDiameterMm =>
      columnsByName['aperture_diameter_mm']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get maxExposureS =>
      columnsByName['max_exposure_s']! as i1.GeneratedColumn<double>;
}

i1.GeneratedColumn<double> _column_78(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'aperture_diameter_mm',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_79(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'max_exposure_s',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );

final class Schema15 extends i0.VersionedSchema {
  Schema15({required super.database}) : super(version: 15);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    devices,
    cameraModules,
    opticalRigs,
    locationProfiles,
    astroTargets,
    sessionLogs,
    captureBlocks,
    astroTargetsCatalogIdUnique,
  ];
  late final Shape1 devices = Shape1(
    source: i0.VersionedTable(
      entityName: 'devices',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_2, _column_13, _column_14],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 cameraModules = Shape12(
    source: i0.VersionedTable(
      entityName: 'camera_modules',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_60,
        _column_1,
        _column_2,
        _column_13,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_11,
        _column_75,
        _column_80,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 opticalRigs = Shape13(
    source: i0.VersionedTable(
      entityName: 'optical_rigs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_61,
        _column_22,
        _column_10,
        _column_23,
        _column_24,
        _column_78,
        _column_79,
        _column_75,
        _column_80,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 locationProfiles = Shape9(
    source: i0.VersionedTable(
      entityName: 'location_profiles',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_25,
        _column_26,
        _column_27,
        _column_67,
        _column_68,
        _column_69,
        _column_70,
        _column_71,
        _column_72,
        _column_73,
        _column_14,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 astroTargets = Shape10(
    source: i0.VersionedTable(
      entityName: 'astro_targets',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_74,
        _column_75,
        _column_76,
        _column_77,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 sessionLogs = Shape6(
    source: i0.VersionedTable(
      entityName: 'session_logs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_52,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 captureBlocks = Shape8(
    source: i0.VersionedTable(
      entityName: 'capture_blocks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_62,
        _column_54,
        _column_55,
        _column_56,
        _column_57,
        _column_58,
        _column_63,
        _column_64,
        _column_65,
        _column_66,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index astroTargetsCatalogIdUnique = i1.Index(
    'astro_targets_catalog_id_unique',
    'CREATE UNIQUE INDEX astro_targets_catalog_id_unique ON astro_targets (catalog_id) WHERE source LIKE \'seed:%\' OR source LIKE \'catalog:%\'',
  );
}

class Shape12 extends i0.VersionedTable {
  Shape12({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get deviceId =>
      columnsByName['device_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get manufacturer =>
      columnsByName['manufacturer']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get model =>
      columnsByName['model']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get sensorWidthMm =>
      columnsByName['sensor_width_mm']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get sensorHeightMm =>
      columnsByName['sensor_height_mm']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get resolutionWidthPx =>
      columnsByName['resolution_width_px']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get resolutionHeightPx =>
      columnsByName['resolution_height_px']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get pixelPitchUm =>
      columnsByName['pixel_pitch_um']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get averageRawFileSizeMB =>
      columnsByName['average_raw_file_size_m_b']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get source =>
      columnsByName['source']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get confidence =>
      columnsByName['confidence']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_80(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'confidence',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape13 extends i0.VersionedTable {
  Shape13({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get cameraModuleId =>
      columnsByName['camera_module_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get focalLengthMm =>
      columnsByName['focal_length_mm']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get aperture =>
      columnsByName['aperture']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get trackingState =>
      columnsByName['tracking_state']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get rotationDegrees =>
      columnsByName['rotation_degrees']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get apertureDiameterMm =>
      columnsByName['aperture_diameter_mm']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get maxExposureS =>
      columnsByName['max_exposure_s']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get source =>
      columnsByName['source']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get confidence =>
      columnsByName['confidence']! as i1.GeneratedColumn<String>;
}

final class Schema16 extends i0.VersionedSchema {
  Schema16({required super.database}) : super(version: 16);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    devices,
    cameraModules,
    opticalRigs,
    locationProfiles,
    astroTargets,
    sessionLogs,
    captureBlocks,
    astroTargetsCatalogIdUnique,
    sessionLogsStatus,
    sessionLogsEveningDate,
    sessionLogsTargetId,
  ];
  late final Shape1 devices = Shape1(
    source: i0.VersionedTable(
      entityName: 'devices',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_2, _column_13, _column_14],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 cameraModules = Shape12(
    source: i0.VersionedTable(
      entityName: 'camera_modules',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_60,
        _column_1,
        _column_2,
        _column_13,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_11,
        _column_75,
        _column_80,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 opticalRigs = Shape13(
    source: i0.VersionedTable(
      entityName: 'optical_rigs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_61,
        _column_22,
        _column_10,
        _column_23,
        _column_24,
        _column_78,
        _column_79,
        _column_75,
        _column_80,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 locationProfiles = Shape9(
    source: i0.VersionedTable(
      entityName: 'location_profiles',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_25,
        _column_26,
        _column_27,
        _column_67,
        _column_68,
        _column_69,
        _column_70,
        _column_71,
        _column_72,
        _column_73,
        _column_14,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 astroTargets = Shape10(
    source: i0.VersionedTable(
      entityName: 'astro_targets',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_74,
        _column_75,
        _column_76,
        _column_77,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 sessionLogs = Shape14(
    source: i0.VersionedTable(
      entityName: 'session_logs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_52,
        _column_81,
        _column_82,
        _column_83,
        _column_84,
        _column_85,
        _column_86,
        _column_87,
        _column_88,
        _column_89,
        _column_90,
        _column_91,
        _column_92,
        _column_93,
        _column_94,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape15 captureBlocks = Shape15(
    source: i0.VersionedTable(
      entityName: 'capture_blocks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_62,
        _column_54,
        _column_55,
        _column_56,
        _column_57,
        _column_58,
        _column_63,
        _column_64,
        _column_65,
        _column_66,
        _column_95,
        _column_96,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index astroTargetsCatalogIdUnique = i1.Index(
    'astro_targets_catalog_id_unique',
    'CREATE UNIQUE INDEX astro_targets_catalog_id_unique ON astro_targets (catalog_id) WHERE source LIKE \'seed:%\' OR source LIKE \'catalog:%\'',
  );
  final i1.Index sessionLogsStatus = i1.Index(
    'session_logs_status',
    'CREATE INDEX session_logs_status ON session_logs (status)',
  );
  final i1.Index sessionLogsEveningDate = i1.Index(
    'session_logs_evening_date',
    'CREATE INDEX session_logs_evening_date ON session_logs (evening_date)',
  );
  final i1.Index sessionLogsTargetId = i1.Index(
    'session_logs_target_id',
    'CREATE INDEX session_logs_target_id ON session_logs (target_id)',
  );
}

class Shape14 extends i0.VersionedTable {
  Shape14({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get targetName =>
      columnsByName['target_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get equipmentName =>
      columnsByName['equipment_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get sessionDate =>
      columnsByName['session_date']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get locationName =>
      columnsByName['location_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get bortleScale =>
      columnsByName['bortle_scale']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get plannedLightFrames =>
      columnsByName['planned_light_frames']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get plannedDarkFrames =>
      columnsByName['planned_dark_frames']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get plannedFlatFrames =>
      columnsByName['planned_flat_frames']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get plannedBiasFrames =>
      columnsByName['planned_bias_frames']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get integrationTimeSeconds =>
      columnsByName['integration_time_seconds']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get focalLength =>
      columnsByName['focal_length']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get aperture =>
      columnsByName['aperture']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get temperature =>
      columnsByName['temperature']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get humidity =>
      columnsByName['humidity']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get cloudCover =>
      columnsByName['cloud_cover']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get actualLightFrames =>
      columnsByName['actual_light_frames']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get rejectedFrames =>
      columnsByName['rejected_frames']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get environmentalNotes =>
      columnsByName['environmental_notes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get processingNotes =>
      columnsByName['processing_notes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get legacy =>
      columnsByName['legacy']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get eveningDate =>
      columnsByName['evening_date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get timeZoneId =>
      columnsByName['time_zone_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get siteId =>
      columnsByName['site_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get targetId =>
      columnsByName['target_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get rigId =>
      columnsByName['rig_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAtUtcMs =>
      columnsByName['created_at_utc_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAtUtcMs =>
      columnsByName['updated_at_utc_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get plannedAtUtcMs =>
      columnsByName['planned_at_utc_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get startedAtUtcMs =>
      columnsByName['started_at_utc_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get completedAtUtcMs =>
      columnsByName['completed_at_utc_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get planSnapshot =>
      columnsByName['plan_snapshot']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get executionStartSnapshot =>
      columnsByName['execution_start_snapshot']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_81(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'draft\' CHECK (status IN (\'draft\', \'planned\', \'inProgress\', \'completed\', \'abandoned\'))',
      defaultValue: const i1.CustomExpression('\'draft\''),
    );
i1.GeneratedColumn<int> _column_82(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'legacy',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (legacy IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_83(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'evening_date',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_84(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'time_zone_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_85(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'site_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NULL REFERENCES location_profiles(id)ON DELETE SET NULL',
    );
i1.GeneratedColumn<int> _column_86(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'target_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL REFERENCES astro_targets(id)ON DELETE SET NULL',
    );
i1.GeneratedColumn<int> _column_87(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'rig_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL REFERENCES optical_rigs(id)ON DELETE SET NULL',
    );
i1.GeneratedColumn<int> _column_88(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'created_at_utc_ms',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_89(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'updated_at_utc_ms',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_90(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'planned_at_utc_ms',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_91(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'started_at_utc_ms',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_92(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'completed_at_utc_ms',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_93(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'plan_snapshot',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_94(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'execution_start_snapshot',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape15 extends i0.VersionedTable {
  Shape15({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get sessionLogId =>
      columnsByName['session_log_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get frameType =>
      columnsByName['frame_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get filterName =>
      columnsByName['filter_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get exposureTimeSeconds =>
      columnsByName['exposure_time_seconds']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get frameCount =>
      columnsByName['frame_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get binning =>
      columnsByName['binning']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get position =>
      columnsByName['position']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get calibrationPolicy =>
      columnsByName['calibration_policy']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get gainKind =>
      columnsByName['gain_kind']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get gainValue =>
      columnsByName['gain_value']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get completedFrames =>
      columnsByName['completed_frames']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get rejectedFrames =>
      columnsByName['rejected_frames']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_95(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'completed_frames',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_96(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'rejected_frames',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema9 schema) from8To9,
  required Future<void> Function(i1.Migrator m, Schema10 schema) from9To10,
  required Future<void> Function(i1.Migrator m, Schema11 schema) from10To11,
  required Future<void> Function(i1.Migrator m, Schema12 schema) from11To12,
  required Future<void> Function(i1.Migrator m, Schema13 schema) from12To13,
  required Future<void> Function(i1.Migrator m, Schema14 schema) from13To14,
  required Future<void> Function(i1.Migrator m, Schema15 schema) from14To15,
  required Future<void> Function(i1.Migrator m, Schema16 schema) from15To16,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 8:
        final schema = Schema9(database: database);
        final migrator = i1.Migrator(database, schema);
        await from8To9(migrator, schema);
        return 9;
      case 9:
        final schema = Schema10(database: database);
        final migrator = i1.Migrator(database, schema);
        await from9To10(migrator, schema);
        return 10;
      case 10:
        final schema = Schema11(database: database);
        final migrator = i1.Migrator(database, schema);
        await from10To11(migrator, schema);
        return 11;
      case 11:
        final schema = Schema12(database: database);
        final migrator = i1.Migrator(database, schema);
        await from11To12(migrator, schema);
        return 12;
      case 12:
        final schema = Schema13(database: database);
        final migrator = i1.Migrator(database, schema);
        await from12To13(migrator, schema);
        return 13;
      case 13:
        final schema = Schema14(database: database);
        final migrator = i1.Migrator(database, schema);
        await from13To14(migrator, schema);
        return 14;
      case 14:
        final schema = Schema15(database: database);
        final migrator = i1.Migrator(database, schema);
        await from14To15(migrator, schema);
        return 15;
      case 15:
        final schema = Schema16(database: database);
        final migrator = i1.Migrator(database, schema);
        await from15To16(migrator, schema);
        return 16;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema9 schema) from8To9,
  required Future<void> Function(i1.Migrator m, Schema10 schema) from9To10,
  required Future<void> Function(i1.Migrator m, Schema11 schema) from10To11,
  required Future<void> Function(i1.Migrator m, Schema12 schema) from11To12,
  required Future<void> Function(i1.Migrator m, Schema13 schema) from12To13,
  required Future<void> Function(i1.Migrator m, Schema14 schema) from13To14,
  required Future<void> Function(i1.Migrator m, Schema15 schema) from14To15,
  required Future<void> Function(i1.Migrator m, Schema16 schema) from15To16,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(
    from8To9: from8To9,
    from9To10: from9To10,
    from10To11: from10To11,
    from11To12: from11To12,
    from12To13: from12To13,
    from13To14: from13To14,
    from14To15: from14To15,
    from15To16: from15To16,
  ),
);
